# Problem 5.4.2 
The algorithm for computing softmax(Z) involves subtracting the maximum of Z in each column from the entries of that column before taking the exponential. What is wrong with subtracting the maximum of Z for the entire matrix from the entries of Z before taking the exponential? 

**Hint:** see what happens when this alternative approach is applied to the following matrix:

$Z = \begin{bmatrix} 1000 & -1000 & 0 \\ -500 & 500 & 250 \end{bmatrix}$

In [1]:
import numpy as np

In [2]:
def softmax1(Z):
    """This function subtracts the max over the entire matrix Z before taking the exponential"""
    Zmax = np.max(Z)
    numerator = np.exp(Z-Zmax)
    denominator = np.sum(numerator,axis=0,keepdims=True)
    return numerator/denominator

In [3]:
Z = np.array([[1000,-1000,0],[-500,500,250]])
Z

array([[ 1000, -1000,     0],
       [ -500,   500,   250]])

In [4]:
soft1 = softmax1(Z)
soft1

/Users/kristokrugger/.local/lib/python3.7/site-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in true_divide
  


array([[ 1.,  0., nan],
       [ 0.,  1., nan]])

In [9]:
def softmax2(Z):
    """This function subtracts the max over the columns of matrix Z before taking the exponential"""
    Zmax_col = np.amax(Z,axis=0,keepdims=True)
    numerator = np.exp(Z-Zmax_col)
    denominator = np.sum(numerator,axis=0,keepdims=True)
    return numerator/denominator

In [11]:
soft2 = softmax2(Z)
soft2

array([[1.00000000e+000, 0.00000000e+000, 2.66919022e-109],
       [0.00000000e+000, 1.00000000e+000, 1.00000000e+000]])