# One-hot Example

In [1]:
import numpy as np

### Conversion to one-hot

In [2]:
def onehot(Y,nclass):
    ndata = Y.shape[1]
    Y_onehot = np.zeros((nclass,ndata))
    for count in range(ndata):
        Y_onehot[int(Y[0,count]),count] = 1.0
    return Y_onehot

In [3]:
Y = np.array([[0,3,2,0]])
Yonehot = onehot(Y,4)
print("Y: {}".format(Y))
print("Yonehot: \n{}".format(Yonehot))

Y: [[0 3 2 0]]
Yonehot: 
[[1. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]


### Inverse of one-hot

In [4]:
def onehot_inverse(A):
    return np.expand_dims(np.argmax(A,axis=0),axis=0)

In [5]:
A = np.array([[0.2,0.3,0.4,0.3],[0.4,0.5,0.1,0.2],[0.0,0.1,0.3,0.4],[0.4,0.1,0.2,0.1]])
inverse = onehot_inverse(A)
print("A: \n{}".format(A))
print("inverse: \n{}".format(inverse))

A: 
[[0.2 0.3 0.4 0.3]
 [0.4 0.5 0.1 0.2]
 [0.  0.1 0.3 0.4]
 [0.4 0.1 0.2 0.1]]
inverse: 
[[1 1 0 2]]
