# sklearn Demo
Demo of text processing functionality in sklearn

In [1]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

### Create messages
List of 3 messages

In [2]:
#dataset
list_message = ["Call me soon", "CALL to win", "Pick me up soon"]

### Process text
Create instance of Countvectorizer and process text

In [3]:
# Create instance of vectorizer
vectorizer = CountVectorizer(decode_error="ignore")
# Perform word counts
Xfit = vectorizer.fit_transform(list_message)
# Generate feature matrix (transform so sample axis is along columns)
X = Xfit.toarray().T
print("X: \n{}".format(X))
# list words in vocabulary (turn into numpy array)
vocabulary = np.array(vectorizer.get_feature_names())
print("Vocabulary: {}".format(vocabulary))

X: 
[[1 1 0]
 [1 0 1]
 [0 0 1]
 [1 0 1]
 [0 1 0]
 [0 0 1]
 [0 1 0]]
Vocabulary: ['call' 'me' 'pick' 'soon' 'to' 'up' 'win']


### Word Count
Sum in col direction to get total count of words in all messages

In [4]:
totalcount = np.sum(X,axis=1,keepdims=True)
print("totalcount: \n{}".format(totalcount))

totalcount: 
[[2]
 [2]
 [1]
 [2]
 [1]
 [1]
 [1]]


### Most Common Words
Determine indices of most common words and list most common words

In [5]:
# get indices of nmostcommon words using argsort
nmostcommon = 4
idx = np.argsort(-np.squeeze(totalcount))[:nmostcommon]
print("Index of most common words: {}".format(idx))
print("Vocabulary: {}".format(vocabulary))
wordsmostcommon = vocabulary[idx]
print("nmostcommon words: {}".format(wordsmostcommon))

Index of most common words: [0 1 3 2]
Vocabulary: ['call' 'me' 'pick' 'soon' 'to' 'up' 'win']
nmostcommon words: ['call' 'me' 'soon' 'pick']
