# Problem 2.6.1 
Consider the messages:

“A bird in the hand is worth 2 in the bush”

“The early bird gets the worm”

“A cat has nine lives”

“Honesty is the best policy”

Repeat the countvectorizer example in [IntroML/Examples/Chapter2/sklearnDemo.ipynb](https://github.com/satishchandrareddy/IntroML/blob/master/Examples/Chapter2/sklearnDemo.ipynb) using stop words (“the”, “a”, “is” “in”).


In [1]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [6]:
list_message = [
    "A bird in the hand is worth 2 in the bush", 
    "The early bird gets the worm", 
    "A cat has nine lives",
    "Honesty is the best policy"
]

stop_words = ["the", "a", "is", "in"]

In [17]:
# Create instance of vectorizer
vectorizer = CountVectorizer(decode_error="ignore", stop_words=stop_words)
# Perform word counts
Xfit = vectorizer.fit_transform(list_message)
# Generate feature matrix (transform so sample axis is along columns)
X = Xfit.toarray().T
print("X: \n{}".format(X))
# list words in vocabulary (turn into numpy array)
words = np.array(vectorizer.get_feature_names())
print("Words: {}".format(words))
print("Stop Words: {}".format(vectorizer.stop_words))

X: 
[[0 0 0 1]
 [1 1 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 1 0 0]
 [1 0 0 0]]
Words: ['best' 'bird' 'bush' 'cat' 'early' 'gets' 'hand' 'has' 'honesty' 'lives'
 'nine' 'policy' 'worm' 'worth']
Stop Words: ['the', 'a', 'is', 'in']


In [9]:
totalcount = np.sum(X,axis=1,keepdims=True)
print("totalcount: \n{}".format(totalcount))

totalcount: 
[[1]
 [2]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [10]:
# x is numpy array
x = np.array([1.1,0.1,4.1,5.2,4.1])
print("x: {}".format(x))

x: [1.1 0.1 4.1 5.2 4.1]


In [11]:
# indices of sorted entries in ascending order [1,0,2,4,3]
# argsort gives indices of sorted entries in ascending order (choose lowest index first in case of ties)
idx_ascending = np.argsort(x)
print("Indices of entries sorted in ascending order: {}".format(idx_ascending))

Indices of entries sorted in ascending order: [1 0 2 4 3]


In [12]:
# indices of sorted entries in descending order [3,2,4,0,1]
# argsort(-x) gives indcies of sorted entries in descending order (choose lowest index first in case of ties)
idx_descending = np.argsort(-x)
print("Indices of entries sorted in descending order: {}".format(idx_descending))

Indices of entries sorted in descending order: [3 2 4 0 1]


In [13]:
# get indices of most common words using argsort
print("total count: {}".format(np.squeeze(totalcount)))
idx = np.argsort(-np.squeeze(totalcount))
print("Sorted index of most common words: {}".format(idx))

total count: [1 2 1 1 1 1 1 1 1 1 1 1 1 1]
Sorted index of most common words: [ 1  0  2  3  4  5  6  7  8  9 10 11 12 13]


In [15]:
# determine 4 most common words
nmostcommon = 4
print("Words: {}".format(words))
idx = idx[:nmostcommon]
print("Sorted index of {} most common words: {}".format(nmostcommon,idx))
wordsmostcommon = words[idx]
print("nmostcommon=4 words: {}".format(wordsmostcommon))

Words: ['best' 'bird' 'bush' 'cat' 'early' 'gets' 'hand' 'has' 'honesty' 'lives'
 'nine' 'policy' 'worm' 'worth']
Sorted index of 4 most common words: [1 0 2 3]
nmostcommon=4 words: ['bird' 'best' 'bush' 'cat']
