# Problem 2.1.1

Let $X = \begin{bmatrix} 1 & 2 & 4 \\ -2 & -5 &-8 \end{bmatrix}, Y = \begin{bmatrix} 1 & 2 & 3 \end{bmatrix}, Z = \begin{bmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 7  \end{bmatrix}$

### Perform the following numpy operations:

**(a)** Define each of X, Y and Z as a 2d numpy array.

In [28]:
import numpy as np

In [13]:
X = np.array([[1, 2, 4], [-2, -5, -8]])
X

array([[ 1,  2,  4],
       [-2, -5, -8]])

In [14]:
Y = np.array([[1, 2, 3]])
Y

array([[1, 2, 3]])

In [15]:
Z = np.array([[1, 2], [3, 4], [5,7]])
Z

array([[1, 2],
       [3, 4],
       [5, 7]])

**(b)**	Concatenate X and Y in the row direction (X on top of Y).

In [17]:
XYrow = np.concatenate((X, Y), axis=0)
XYrow

array([[ 1,  2,  4],
       [-2, -5, -8],
       [ 1,  2,  3]])

**(c)**	Concatenate X and $Z^T$ in the column direction (X then Z). Hint: use the .T attribute for the transpose.

In [18]:
XZTcol = np.concatenate((X, Z.T), axis=1)
XZTcol

array([[ 1,  2,  4,  1,  3,  5],
       [-2, -5, -8,  2,  4,  7]])

**(d)**	Concatenate X, Y and $Z^T$  in the row direction.

In [20]:
XYZTrow = np.concatenate((X, Y, Z.T), axis=0)
XYZTrow

array([[ 1,  2,  4],
       [-2, -5, -8],
       [ 1,  2,  3],
       [ 1,  3,  5],
       [ 2,  4,  7]])

**(e)**	Reshape Z into a 2x3 matrix and compute X +3*reshapedZ.

In [21]:
reshapedZ = Z.reshape((2, 3))
reshapedZ

array([[1, 2, 3],
       [4, 5, 7]])

In [22]:
result = X + 3*reshapedZ
result

array([[ 4,  8, 13],
       [10, 10, 13]])

**(f)**	Reshape Z into a 2x3 matrix and compute X*reshapedZ (component-wise multiplication).

In [25]:
cwmresult = X*reshapedZ
cwmresult

array([[  1,   4,  12],
       [ -8, -25, -56]])

**(g)**	Sum Z in the row direction.

In [26]:
Zrowsum = np.sum(Z, axis=0)
Zrowsum

array([ 9, 13])

**(h)**	Sum Z in the column direction.

In [27]:
Zcolsum = np.sum(Z, axis=1)
Zcolsum

array([ 3,  7, 12])