# Linear Algebra With NumPy Demo
This demo covers the basics of linear algebra operations using NumPy, check out the [documentation](https://numpy.org/doc/stable/reference/routines.linalg.html) to learn more.

In [ ]:
import numpy as np

## Transpose
Use the T attribute to take transpose of a numpy array

In [ ]:
# transpose example 1
# W = [1 2 3 4]
W = np.array([[1,2,3,4]])
print("W: \n{}".format(W))
print("W transpose: \n{}".format(W.T))

In [ ]:
# transpose example 2
# X = [1  2  3  4]
#     [5  6  7  8]
#     [9 10 11 12]
X = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("X: \n{}".format(X))
print("X transpose: \n{}".format(X.T))

## Matrix Multiplication
Use np.dot() for matrix mulitplication

In [ ]:
# matrix multiplication example 1
# W = [1 2 3]
# X = [4 7]
#     [5 8]
#     [6 9]
W = np.array([[1,2,3]])
X = np.array([[4,7],[5,8],[6,9]])
Z = np.dot(W,X)
print("Matrix Multiplication Example 1")
print("W: \n{}".format(W))
print("X: \n{}".format(X))
print("Z: \n{}".format(Z))

In [ ]:
# matrix multiplication example 2
# W = [1 2 3]
#     [2 3 4]
# X = [4 7]
#     [5 8]
#     [6 9]
W = np.array([[1,2,3],[2,3,4]])
X = np.array([[4,7],[5,8],[6,9]])
Z = np.dot(W,X)
print("Matrix Multiplication Example 2")
print("W: \n{}".format(W))
print("X: \n{}".format(X))
print("Z: \n{}".format(Z))

## Broadcasting
To learn more about broadcasting, click [here](https://www.tutorialspoint.com/numpy/numpy_broadcasting.htm#:~:text=Selected%20Reading-,NumPy%20%2D%20Broadcasting,usually%20done%20on%20corresponding%20elements.).

In [ ]:
# broadcasting example 1
# W = [1 2 3]
# X = [4 7]
#     [5 8]
#     [6 9]
W = np.array([[1,2,3]])
X = np.array([[4,7],[5,8],[6,9]])
b = 7
Z = np.dot(W,X)+b
print("Matrix Multiplication Example 1")
print("W: \n{}".format(W))
print("X: \n{}".format(X))
print("b: {}".format(b))
print("Z: \n{}".format(Z))

In [ ]:
# broadcasting example 2
# W = [1 2 3]
#     [2 3 4]
# X = [4 7]
#     [5 8]
#     [6 9]
# b = [11]
#     [12]
W = np.array([[1,2,3],[2,3,4]])
X = np.array([[4,7],[5,8],[6,9]])
b = np.array([[11],[12]])
Z = np.dot(W,X)+b
print("Matrix Multiplication Example 2")
print("W: \n{}".format(W))
print("X: \n{}".format(X))
print("b: \n{}".format(b))
print("Z: \n{}".format(Z))