In [ ]:
# import numpy
import numpy as np

In [ ]:
# transpose example 1
# W = [1 2 3 4]
W = np.array([[1,2,3,4]])
print("W: \n{}".format(W))
print("W transpose: \n{}".format(W.T))

In [ ]:
# transpose example 2
# X = [1  2  3  4]
#     [5  6  7  8]
#     [9 10 11 12]
X = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("X: \n{}".format(X))
print("X transpose: \n{}".format(X.T))

In [ ]:
# matrix multiplication example 1
# W = [1 2 3]
# X = [4 7]
#     [5 8]
#     [6 9]
W = np.array([[1,2,3]])
X = np.array([[4,7],[5,8],[6,9]])
Z = np.dot(W,X)
print("Matrix Multiplication Example 1")
print("W: \n{}".format(W))
print("X: \n{}".format(X))
print("Z: \n{}".format(Z))

In [ ]:
# matrix multiplication example 2
# W = [1 2 3]
#     [2 3 4]
# X = [4 7]
#     [5 8]
#     [6 9]
W = np.array([[1,2,3],[2,3,4]])
X = np.array([[4,7],[5,8],[6,9]])
Z = np.dot(W,X)
print("Matrix Multiplication Example 2")
print("W: \n{}".format(W))
print("X: \n{}".format(X))
print("Z: \n{}".format(Z))

In [ ]:
# broadcasting example 1
# W = [1 2 3]
# X = [4 7]
#     [5 8]
#     [6 9]
W = np.array([[1,2,3]])
X = np.array([[4,7],[5,8],[6,9]])
b = 7
Z = np.dot(W,X)+b
print("Matrix Multiplication Example 1")
print("W: \n{}".format(W))
print("X: \n{}".format(X))
print("b: {}".format(b))
print("Z: \n{}".format(Z))

In [ ]:
# broadcasting example 2
# W = [1 2 3]
#     [2 3 4]
# X = [4 7]
#     [5 8]
#     [6 9]
# b = [11]
#     [12]
W = np.array([[1,2,3],[2,3,4]])
X = np.array([[4,7],[5,8],[6,9]])
b = np.array([[11],[12]])
Z = np.dot(W,X)+b
print("Matrix Multiplication Example 2")
print("W: \n{}".format(W))
print("X: \n{}".format(X))
print("b: \n{}".format(b))
print("Z: \n{}".format(Z))