In [ ]:
#Chapter1.4_NumpyDemo
import numpy as np

In [ ]:
# convert list to numpy array
a = np.array([2,7,1])
print("1d array: a: {}".format(a))
print("1d array: a.shape: {}".format(a.shape))
print("Index into array entry index 2: {}".format(a[2]))

In [ ]:
# example: 2d-array as row vector
# A = [2,7,1]
# Define A as list of list for each row
A = np.array([[2,7,1]])
print("2d row matrix: A: {}".format(A))
print("2d row matrix: A.shape: {}".format(A.shape))
print("Index into matrix entry index row=0,col=2: {}".format(A[0,2]))

In [ ]:
# example: 2d-array as column vector
# each row is a list
# Define B as list of list for each row
# B = [2]
#     [7]
#     [1]
B = np.array([[1],[2],[3]])
print("2d column matrix: B: \n{}".format(B))
print("2d column matrix: B.shape: {}".format(B.shape))
print("Index into matrix entry index row=1,col=0: {}".format(B[1,0]))

In [ ]:
# example: matrix
# X = [1 2 3]
#     [4 5 6]
# Define X as list of list for each row
X = np.array([[1,2,3],[4,5,6]])
print("2d array: X: \n{}".format(X))
print("2d array: X.shape: {}".format(X.shape))
print("Index into marix entry index row=1,col=1: {}".format(X[1,1]))

In [ ]:
# componentwise operations
# X = [1 2 3]
#     [4 5 6]
# Y = [1 -1  2]
#     [2  3 -2]
X = np.array([[1,2,3],[4,5,6]])
Y = np.array([[1,-1,2],[2,3,-2]])
print("X: \n{}".format(X))
print("Y: \n{}".format(Y))

In [ ]:
# componentwise addition
Z1=X + Y
print("Z1=X+Y: \n{}".format(Z1))

In [ ]:
# scalar multiplication
Z2 = 2*X
print("Z2=2*X: \n{}".format(Z2))

In [ ]:
# componentwise multiplication (not matrix multiplication)
Z3 = X*Y
print("Z3=X*Y: \n{}".format(Z3))

In [ ]:
# numpy functions - exponential
Xexp = np.exp(X)
print("Exponential of X: \n{}".format(Xexp))

In [ ]:
# numpy functions - absolute value
Yabs = np.absolute(Y)
print("Absolute Value of Y: \n{}".format(Yabs))

In [ ]:
# numpy functions - square
Xsq = np.square(X)
print("Square of X: \n{}".format(Xsq))

In [ ]:
# concatenation
X = np.array([[1,2,3],[4,5,6]])
Y = np.array([[1,-1,2],[2,3,-2]])
print("X: \n{}".format(X))
print("Y: \n{}".format(Y))
# concatenation - in row direction - use axis=0 in 2nd input
# result is [1  2  3]
#           [4  5  6]
#           [1 -1  2]
#           [2  3 -2]
XandYrow = np.concatenate((X,Y),axis=0)
print("X and Y concatenated in row direction: \n{}".format(XandYrow))
# concatenation X and Y - in column direction - use axis=1 in 2nd input
# result is [1 2 3 1 -1  2]
#           [4 5 6 2  3 -2]
XandYcol = np.concatenate((X,Y),axis=1)
print("X and Y concatenated in column direction: \n{}".format(XandYcol))

In [ ]:
# reshape X into matrix 1 row 6 columns: [1 2 3 4 5 6]
Xreshaperow = np.reshape(X,(1,6))
print("X reshape row vector: \n{}".format(Xreshaperow))
Xreshapecol = np.reshape(X,(6,1))
print("X reshape col vector: \n{}".format(Xreshapecol))

In [ ]:
# start with row vector (2d np.array) and convert to 1d np.array
A = np.array([[1,2,3]])
print("A: {}".format(A))
print("A.shape: {}".format(A.shape))
# removes axis with only 1 entry in dimension
A1 = np.squeeze(A) 
print("A1: {}".format(A1))
print("A1.shape: {}".format(A1.shape))

In [ ]:
# start with 1d array and make into 2d array using np.expand_dims
a = np.array([1,2,3])
print("a: {}".format(a))
print("a.shape: {}".format(a))
# add dimension to make into a row vector
b = np.expand_dims(a,axis=0)
print("b: \n{}".format(b))
print("b.shape: {}".format(b.shape))
# add dimension to make into a column vector 
c = np.expand_dims(a,axis=1)
print("c: \n{}".format(c))
print("c.shape: {}".format(c.shape))

In [ ]:
# X = [1 2 3]
#     [4 5 6]
X = np.array([[1,2,3],[4,5,6]])
print("X: \n{}".format(X))
# sum all entries
sum1 = np.sum(X)
print("sum entries of x: {}".format(sum1))

In [ ]:
# sum in row direction - this removes an axis -> 1d array [5 7 9]
rowsum1 = np.sum(X,axis=0)
print("sum in row direction X: \n{}".format(rowsum1))
print("rowsum1.shape: {}".format(rowsum1.shape))

In [ ]:
# sum in row direction - keep row axis -> row matrix [5 7 9]
rowsum2 = np.sum(X,axis=0,keepdims=True)
print("sum in row direction X keep row axis: \n{}".format(rowsum2))
print("rowsum2.shape: {}".format(rowsum2.shape))

In [ ]:
# sum in column direction - keep column axis -> 2darray
colsum1 = np.sum(X,axis=1,keepdims=True)
print("sum in column direction keep col axis: \n{}".format(colsum1))
print("colsum1.shape: {}".format(colsum1.shape))

In [ ]:
# generate zero matrix dimension (3,2)
Z0 = np.zeros((3,2))
print("zero matrix: \n{}".format(Z0))
# generate ones matrix dimension (2,3)
Z1 = np.ones((2,3))
print("ones marrix: \n{}".format(Z1))

In [ ]:
# generate random matrix  dim (2,3) - uniform distribution
Runiform = np.random.rand(2,3)
print("Runiform: \n{}".format(Runiform))

In [ ]:
# generate random matrix  dim (2,3) - normal distribution
# set seed first
np.random.seed(10)
Rnormal = np.random.randn(2,3)
print("Runiform: \n{}".format(Rnormal))