# Problem 3.1.1

Let $X = \begin{bmatrix} 1 & 2 & 4 \\ -2 & -5 &-8 \end{bmatrix}, Y = \begin{bmatrix} 1 & 2 & 3 \end{bmatrix}, Z = \begin{bmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 7  \end{bmatrix}$

### Compute:

**(a)** X + Y

In [4]:
import numpy as np

In [5]:
X = np.array([[1, 2, 4], [-2, -5, -8]])
Y = np.array([[1, 2, 3]])
Z = np.array([[1, 2], [3, 4], [5,7]])

In [6]:
result = X + Y
result

array([[ 2,  4,  7],
       [-1, -3, -5]])

**(b)** Z + $Y^T$

In [7]:
result = Z + Y.T
result

array([[ 2,  3],
       [ 5,  6],
       [ 8, 10]])

**(c)** XZ

In [8]:
result = np.dot(X,Z)
result

array([[ 27,  38],
       [-57, -80]])

**(d)** X + $Z^T$

In [9]:
result = X + Z.T
result

array([[ 2,  5,  9],
       [ 0, -1, -1]])

**(e)** ZX

In [10]:
result = np.dot(Z,X)
result

array([[ -3,  -8, -12],
       [ -5, -14, -20],
       [ -9, -25, -36]])

**(f)** $X^TZ^T$

In [11]:
result = np.dot(X.T,Z.T)
result

array([[ -3,  -5,  -9],
       [ -8, -14, -25],
       [-12, -20, -36]])

**(g)** ZX + Y

In [15]:
result = np.dot(Z,X) + Y
result

array([[ -2,  -6,  -9],
       [ -4, -12, -17],
       [ -8, -23, -33]])